### ISSUE TITLE
Greetings from CONTROLLINO!

### ISSUE THREAD

**Issue by ControllinoAdmin** [ATT-JBO/controllino_lights_control#1]
Hi Jan,

great job! 🥇 

Please note that CONTROLLINO web pages are https://controllino.biz/ 
May I ask you to update your readme accordingly, please?

Thanks,
Best regards,
Lukas from CONTROLLINO team

**Comment by jan-bogaerts** [comment]
Hi,

thanks for the heads-up. I've updated the link.

Note: I'll be changing this project soon so that it can connect with the 
home-assistant gateway (https://home-assistant.io/) for better 
compatibility and interoperability with other systems.

Cheers,
Jan.

------ Original Message ------
