### ISSUE TITLE
Nice code, thanks!

### ISSUE THREAD

**Issue by plckr** [ATT-JBO/controllino_lights_control#2]
Hello, very nice code, I also bought a controllino Mega, I use Home Assistant and want to integrate it with HA via mqtt. Controllino should act even if Home Assistant is offline like yours.
In issue #1 you said you were migrating to Home Assistant, I had like to know if you have something? I made a lookup in your repositories but didn't found anything.

Thanks anyway!

**Comment by jan-bogaerts** [comment]
The device was moved to HA using a standard mqtt channel. The config was hardcoded though cause I didn't have the time anymore for dynamic stuff. I've also moved since and no longer have a controllino, nor the code.
